import {
	ICONS_BACKEND,
	ICONS_FRONTEND,
	ICONS_MOBILE,
	ICONS_PROGRAMMING,
	ICONS_SOFTWARE,
	ICONS_SYSTEM_CONTROL,
	ICONS_TESTING,
} from './constants.ts'

export const devIcons = {
	[ICONS_FRONTEND]: [
		{ icon: 'devicon-html5-plain colored', text: 'html5' },
		{ icon: 'devicon-css3-plain colored', text: 'css3' },
		{ icon: 'devicon-sass-original colored', text: 'sass' },
		{
			icon: 'devicon-bootstrap-plain colored',
			text: 'bootstrap',
		},
		{
			icon: 'devicon-tailwindcss-plain colored',
			text: 'tailwindcss',
		},
		{
			icon: 'devicon-materialui-plain colored',
			text: 'materialui',
		},
		{
			icon: 'devicon-javascript-plain colored',
			text: 'javascript',
		},
		{
			icon: 'devicon-typescript-plain colored',
			text: 'typescript',
		},
		{ icon: 'devicon-react-original colored', text: 'react' },
		{ icon: 'devicon-redux-original colored', text: 'redux' },
		{ icon: 'devicon-nextjs-original colored', text: 'nextjs' },
		{ icon: 'devicon-vuejs-plain colored', text: 'vuejs' },
		{ icon: 'devicon-vuetify-line colored', text: 'vuetify' },
		{ icon: 'devicon-nuxtjs-plain colored', text: 'nuxtjs' },
		{
			icon: 'devicon-angularjs-plain colored',
			text: 'angularjs',
		},
		{ icon: 'devicon-svelte-plain colored', text: 'svelte' },
		{ icon: 'devicon-gulp-plain colored', text: 'gulp' },
		{ icon: 'devicon-webpack-plain colored', text: 'webpack' },
		{ icon: 'devicon-d3js-plain colored', text: 'd3js' },
		{ icon: 'devicon-eslint-original colored', text: 'eslint' },
		{
			icon: 'devicon-wordpress-plain colored',
			text: 'wordpress',
		},
		{
			icon: 'devicon-eleventy-plain colored',
			text: 'eleventy',
		},
		{ icon: 'devicon-babel-plain colored', text: 'babel' },
		{ icon: 'devicon-gatsby-plain colored', text: 'gatsby' },
		{ icon: 'devicon-django-plain colored', text: 'django' },
		{
			icon: 'devicon-markdown-original colored',
			text: 'markdown',
		},
		{
			icon: 'devicon-backbonejs-plain colored',
			text: 'backbonejs',
		},
		{ icon: 'devicon-hugo-plain colored', text: 'hugo' },
		{
			icon: 'devicon-threejs-original colored',
			text: 'threejs',
		},
		{
			icon: 'devicon-magento-original colored',
			text: 'magento',
		},
	],
	[ICONS_BACKEND]: [
		{ icon: 'devicon-nodejs-plain colored', text: 'nodejs' },
		{
			icon: 'devicon-express-original colored',
			text: 'express',
		},
		{ icon: 'devicon-graphql-plain colored', text: 'graphql' },
		{
			icon: 'devicon-apachekafka-original colored',
			text: 'apachekafka',
		},
		{ icon: 'devicon-r-original colored', text: 'r' },
		{ icon: 'devicon-rails-plain colored', text: 'rails' },
		{ icon: 'devicon-nestjs-plain colored', text: 'nestjs' },
		{ icon: 'devicon-nginx-original colored', text: 'nginx' },
		{
			icon: 'devicon-adonisjs-original colored',
			text: 'adonisjs',
		},
		{ icon: 'devicon-pycharm-plain colored', text: 'pycharm' },
		{
			icon: 'devicon-pytorch-original colored',
			text: 'pytorch',
		},
		{ icon: 'devicon-pandas-original colored', text: 'pandas' },
		{ icon: 'devicon-meteor-plain colored', text: 'meteor' },
		{ icon: 'devicon-apache-plain colored', text: 'apache' },
		{ icon: 'devicon-drupal-plain colored', text: 'drupal' },
		{ icon: 'devicon-laravel-plain colored', text: 'laravel' },
		{ icon: 'devicon-flask-original colored', text: 'flask' },
		{
			icon: 'devicon-kubernetes-plain colored',
			text: 'kubernetes',
		},
		{ icon: 'devicon-jenkins-line colored', text: 'jenkins' },
		{ icon: 'devicon-composer-line colored', text: 'composer' },
		{ icon: 'devicon-docker-plain colored', text: 'docker' },
		{
			icon: 'devicon-circleci-plain colored',
			text: 'circleci',
		},
		{
			icon: 'devicon-appwrite-plain colored',
			text: 'appwrite',
		},
		{ icon: 'devicon-bash-plain colored', text: 'bash' },
		{ icon: 'devicon-azure-plain colored', text: 'azure' },
		{
			icon: 'devicon-socketio-original colored',
			text: 'socketio',
		},
		{
			icon: 'devicon-firebase-plain colored',
			text: 'firebase',
		},
		{ icon: 'devicon-cakephp-plain colored', text: 'cakephp' },
		{ icon: 'devicon-mongodb-plain colored', text: 'mongodb' },
		{ icon: 'devicon-mysql-plain colored', text: 'mysql' },
		{
			icon: 'devicon-sqlalchemy-plain colored',
			text: 'sqlalchemy',
		},
		{ icon: 'devicon-sqlite-plain colored', text: 'sqlite' },
		{
			icon: 'devicon-postgresql-plain colored',
			text: 'postgresql',
		},
		{ icon: 'devicon-redis-plain colored', text: 'redis' },
		{ icon: 'devicon-oracle-original colored', text: 'oracle' },
		{ icon: 'devicon-rocksdb-plain colored', text: 'rocksdb' },
		{ icon: 'devicon-couchdb-plain colored', text: 'couchdb' },
	],
	[ICONS_TESTING]: [
		{ icon: 'devicon-jest-plain colored', text: 'jest' },
		{ icon: 'devicon-mocha-plain colored', text: 'mocha' },
		{
			icon: 'devicon-selenium-original colored',
			text: 'selenium',
		},
		{ icon: 'devicon-karma-plain colored', text: 'karma' },
		{ icon: 'devicon-jasmine-plain colored', text: 'jasmine' },
		{ icon: 'devicon-pytest-plain colored', text: 'pytest' },
	],
	[ICONS_PROGRAMMING]: [
		{ icon: 'devicon-c-plain colored', text: 'c' },
		{
			icon: 'devicon-raspberrypi-line colored',
			text: 'raspberrypi',
		},
		{
			icon: 'devicon-cplusplus-plain colored',
			text: 'cplusplus',
		},
		{ icon: 'devicon-csharp-plain colored', text: 'csharp' },
		{
			icon: 'devicon-go-original-wordmark colored',
			text: 'go',
		},
		{
			icon: 'devicon-objectivec-plain colored',
			text: 'objectivec',
		},
		{ icon: 'devicon-java-plain colored', text: 'java' },
		{ icon: 'devicon-rust-plain colored', text: 'rust' },
		{ icon: 'devicon-elixir-plain colored', text: 'elixir' },
		{ icon: 'devicon-php-plain colored', text: 'php' },
		{ icon: 'devicon-perl-plain colored', text: 'perl' },
		{ icon: 'devicon-ruby-plain colored', text: 'ruby' },
		{ icon: 'devicon-scala-plain colored', text: 'scala' },
		{ icon: 'devicon-haskell-plain colored', text: 'haskell' },
		{ icon: 'devicon-erlang-plain colored', text: 'erlang' },
		{ icon: 'devicon-python-plain colored', text: 'python' },
		{ icon: 'devicon-numpy-original colored', text: 'numpy' },
		{ icon: 'devicon-swift-plain colored', text: 'swift' },
		{ icon: 'devicon-clojure-line colored', text: 'clojure' },
		{
			icon: 'devicon-dotnetcore-plain colored',
			text: 'etcore',
		},
	],
	[ICONS_MOBILE]: [
		{ icon: 'devicon-android-plain colored', text: 'android' },
		{ icon: 'devicon-dart-plain colored', text: 'dart' },
		{
			icon: 'devicon-androidstudio-plain colored',
			text: 'androidstudio',
		},
		{ icon: 'devicon-kotlin-plain colored', text: 'kotlin' },
		{
			icon: 'devicon-xamarin-original colored',
			text: 'xamarin',
		},
		{ icon: 'devicon-flutter-plain colored', text: 'flutter' },
		{ icon: 'devicon-ionic-original colored', text: 'ionic' },
	],
	[ICONS_SOFTWARE]: [
		{ icon: 'devicon-xcode-plain colored', text: 'xcode' },
		{
			icon: 'devicon-aftereffects-plain colored',
			text: 'aftereffects',
		},
		{
			icon: 'devicon-photoshop-plain colored',
			text: 'photoshop',
		},
		{
			icon: 'devicon-filezilla-plain colored',
			text: 'filezilla',
		},
		{ icon: 'devicon-figma-plain colored', text: 'figma' },
		{ icon: 'devicon-canva-original colored', text: 'canva' },
		{
			icon: 'devicon-illustrator-plain colored',
			text: 'illustrator',
		},
		{
			icon: 'devicon-phpstorm-plain colored',
			text: 'phpstorm',
		},
		{
			icon: 'devicon-webstorm-plain colored',
			text: 'webstorm',
		},
		{ icon: 'devicon-matlab-plain colored', text: 'matlab' },
		{ icon: 'devicon-sketch-line colored', text: 'sketch' },
		{
			icon: 'devicon-blender-original colored',
			text: 'blender',
		},
		{ icon: 'devicon-unity-original colored', text: 'unity' },
		{ icon: 'devicon-slack-plain colored', text: 'slack' },
		{
			icon: 'devicon-jetbrains-plain colored',
			text: 'jetbrains',
		},
		{ icon: 'devicon-vscode-plain colored', text: 'vscode' },
	],
	[ICONS_SYSTEM_CONTROL]: [
		{ icon: 'devicon-git-plain colored', text: 'git' },
		{ icon: 'devicon-github-original colored', text: 'github' },
		{ icon: 'devicon-gitlab-plain colored', text: 'gitlab' },
		{
			icon: 'devicon-bitbucket-original colored',
			text: 'bitbucket',
		},
		{ icon: 'devicon-jira-plain colored', text: 'jira' },
		{
			icon: 'devicon-confluence-original colored',
			text: 'confluence',
		},
		{ icon: 'devicon-trello-plain colored', text: 'trello' },
		{
			icon: 'devicon-storybook-plain colored',
			text: 'storybook',
		},
	],
}
